INSERT INTO categories (name, slug, description, has_sizes, default_sizes, active) VALUES
  ('Camisetas',        'camisetas',        'Camisetas masculinas e femininas',            true,  'P, M, G, GG, XGG',                          true),
  ('Calças',           'calcas',           'Calças casuais e esportivas',                 true,  'P, M, G, GG, XGG',                          true),
  ('Jaquetas',         'jaquetas',         'Jaquetas e casacos',                          true,  'P, M, G, GG, XGG',                          true),
  ('Moletons',         'moletons',         'Moletons e sweatshirts',                      true,  'P, M, G, GG, XGG',                          true),
  ('Shorts',           'shorts',           'Shorts e bermudas',                           true,  'P, M, G, GG, XGG',                          true),
  ('Vestidos',         'vestidos',         'Vestidos femininos',                          true,  'P, M, G, GG, XGG',                          true),
  ('Saias',            'saias',            'Saias femininas',                             true,  'P, M, G, GG, XGG',                          true),
  ('Blusas',           'blusas',           'Blusas e tops femininos',                     true,  'P, M, G, GG, XGG',                          true),
  ('Camisas',          'camisas',          'Camisas sociais e casuais',                   true,  'P, M, G, GG, XGG',                          true),
  ('Conjuntos',        'conjuntos',        'Conjuntos e coordenados',                     true,  'P, M, G, GG, XGG',                          true),
  ('Leggings',         'leggings',         'Leggings e calças justas',                    true,  'P, M, G, GG, XGG',                          true),
  ('Polos',            'polos',            'Camisas polo masculinas e femininas',         true,  'P, M, G, GG, XGG',                          true),
  ('Tênis',            'tenis',            'Tênis casuais e esportivos',                  true,  '34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44', true),
  ('Sapatos',          'sapatos',          'Sapatos sociais e casuais',                   true,  '34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44', true),
  ('Sandálias',        'sandalias',        'Sandálias e chinelos',                        true,  '34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44', true),
  ('Botas',            'botas',            'Botas e botins',                              true,  '34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44', true),
  ('Bolsas',           'bolsas',           'Bolsas femininas e mochilas',                 false, '',                                          true),
  ('Mochilas',         'mochilas',         'Mochilas e bolsas de costas',                 false, '',                                          true),
  ('Cintos',           'cintos',           'Cintos e acessórios de cintura',              false, '',                                          true),
  ('Bonés',            'bones',            'Bonés e chapéus',                             false, '',                                          true),
  ('Meias',            'meias',            'Meias e meia-calças',                         false, '',                                          true),
  ('Óculos',           'oculos',           'Óculos de sol e de grau',                     false, '',                                          true),
  ('Relógios',         'relogios',         'Relógios e smartwatches',                     false, '',                                          true),
  ('Joias',            'joias',            'Joias e semijoias',                           false, '',                                          true),
  ('Perfumes',         'perfumes',         'Perfumes e fragrâncias',                      false, '',                                          true),
  ('Smartphones',      'smartphones',      'Smartphones e celulares',                     false, '',                                          true),
  ('Fones',            'fones',            'Fones de ouvido e earbuds',                   false, '',                                          true),
  ('Smartwatches',     'smartwatches',     'Relógios inteligentes',                       false, '',                                          true),
  ('Acessórios Tech',  'acessorios-tech',  'Acessórios para dispositivos',                false, '',                                          true),
  ('Lançamentos',      'lancamentos',      'Novidades e lançamentos da temporada',        false, '',                                          true)
ON CONFLICT (slug) DO NOTHING;
